version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/home/jovyan/workspace
      - C:/Users/PC/Desktop/Apache_PySpark_4_workers/Apache_PySpark/notebook:/home/jovyan/workspace/notebook
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/home/jovyan/workspace
      - C:/Users/PC/Desktop/Apache_PySpark_4_workers/Apache_PySpark/notebook:/home/jovyan/workspace/notebook
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2g
      #- SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/home/jovyan/workspace
      - C:/Users/PC/Desktop/Apache_PySpark_4_workers/Apache_PySpark/notebook:/home/jovyan/workspace/notebook
    depends_on:
      - spark-master
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2g
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/home/jovyan/workspace
      - C:/Users/PC/Desktop/Apache_PySpark_4_workers/Apache_PySpark/notebook:/home/jovyan/workspace/notebook
    depends_on:
      - spark-master

  spark-worker-3:
    image: spark-worker
    container_name: spark-worker-3
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2g
    ports:
      - 8083:8081
    volumes:
      - shared-workspace:/home/jovyan/workspace
      - C:/Users/PC/Desktop/Apache_PySpark_4_workers/Apache_PySpark/notebook:/home/jovyan/workspace/notebook
    depends_on:
      - spark-master

  spark-worker-4:
    image: spark-worker
    container_name: spark-worker-4
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2g
    ports:
      - 8084:8081
    volumes:
      - shared-workspace:/home/jovyan/workspace
      - C:/Users/PC/Desktop/Apache_PySpark_4_workers/Apache_PySpark/notebook:/home/jovyan/workspace/notebook
    depends_on:
      - spark-master